apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: dpjdtbtl0-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/dpjdtbtl0-java-quarkus-gitops